"""
word_to_category.py
Maps each English word to one of 8 image categories.
Same word -> same category (deterministic).
"""
import hashlib
import re


# Curated hand mappings (3000+ most common English words)
WORD_TO_CAT = {
    # ===== ANIMALS =====
    "cat": "animal", "dog": "animal", "bird": "animal", "fish": "animal",
    "tiger": "animal", "lion": "animal", "elephant": "animal", "horse": "animal",
    "sheep": "animal", "cow": "animal", "monkey": "animal", "rabbit": "animal",
    "duck": "animal", "chicken": "animal", "snake": "animal", "butterfly": "animal",
    "bee": "animal", "frog": "animal", "octopus": "animal", "whale": "animal",
    "dolphin": "animal", "shark": "animal", "eagle": "animal", "owl": "animal",
    "parrot": "animal", "penguin": "animal", "bear": "animal", "wolf": "animal",
    "deer": "animal", "fox": "animal", "mouse": "animal", "ant": "animal",
    "spider": "animal", "panda": "animal", "koala": "animal", "zebra": "animal",
    "giraffe": "animal", "kangaroo": "animal", "rabbit": "animal", "turtle": "animal",
    "crab": "animal", "shrimp": "animal", "lobster": "animal", "snail": "animal",
    "worm": "animal", "bat": "animal", "rat": "animal", "pig": "animal",
    "goat": "animal", "donkey": "animal", "camel": "animal", "swan": "animal",
    "goose": "animal", "pigeon": "animal", "sparrow": "animal", "crow": "animal",
    "mosquito": "animal", "fly": "animal", "caterpillar": "animal", "lizard": "animal",
    "crocodile": "animal", "hippo": "animal", "rhino": "animal", "leopard": "animal",
    "cheetah": "animal", "jaguar": "animal", "panther": "animal", "hamster": "animal",
    "guinea": "animal", "squirrel": "animal", "chipmunk": "animal", "beaver": "animal",
    "raccoon": "animal", "skunk": "animal", "hedgehog": "animal", "porcupine": "animal",
    "moose": "animal", "buffalo": "animal", "bison": "animal", "yak": "animal",
    "llama": "animal", "alpaca": "animal", "seal": "animal", "otter": "animal",
    "walrus": "animal", "jellyfish": "animal", "starfish": "animal", "seahorse": "animal",
    "eel": "animal", "salmon": "animal", "tuna": "animal", "goldfish": "animal",
    "stingray": "animal", "sturgeon": "animal", "carp": "animal", "minnow": "animal",
    "woodpecker": "animal", "hummingbird": "animal", "flamingo": "animal", "peacock": "animal",
    "robin": "animal", "magpie": "animal", "hawk": "animal", "falcon": "animal",
    "vulture": "animal", "cockatoo": "animal", "canary": "animal", "finch": "animal",
    "beetle": "animal", "ladybug": "animal", "cricket": "animal", "grasshopper": "animal",
    "caterpillar": "animal", "dragonfly": "animal", "firefly": "animal", "termite": "animal",
    "wasp": "animal", "hornet": "animal", "tick": "animal", "flea": "animal",
    "louse": "animal", "moth": "animal",

    # ===== FOOD =====
    "apple": "food", "banana": "food", "orange": "food", "grape": "food",
    "watermelon": "food", "strawberry": "food", "peach": "food", "lemon": "food",
    "pear": "food", "cherry": "food", "pineapple": "food", "mango": "food",
    "bread": "food", "rice": "food", "noodle": "food", "pizza": "food",
    "hamburger": "food", "hotdog": "food", "sandwich": "food", "salad": "food",
    "soup": "food", "cake": "food", "cookie": "food", "icecream": "food",
    "ice": "food", "chocolate": "food", "coffee": "food", "tea": "food",
    "milk": "food", "water": "food", "juice": "food", "beer": "food",
    "wine": "food", "egg": "food", "meat": "food", "vegetable": "food",
    "fruit": "food", "tomato": "food", "potato": "food", "carrot": "food",
    "onion": "food", "cucumber": "food", "corn": "food", "mushroom": "food",
    "pepper": "food", "lettuce": "food", "spinach": "food", "broccoli": "food",
    "cabbage": "food", "pumpkin": "food", "cucumber": "food", "garlic": "food",
    "ginger": "food", "salt": "food", "sugar": "food", "butter": "food",
    "cheese": "food", "yogurt": "food", "cream": "food", "honey": "food",
    "jam": "food", "syrup": "food", "vinegar": "food", "oil": "food",
    "sauce": "food", "ketchup": "food", "mustard": "food", "mayonnaise": "food",
    "pasta": "food", "spaghetti": "food", "macaroni": "food", "lasagna": "food",
    "sushi": "food", "ramen": "food", "dumpling": "food", "springroll": "food",
    "steak": "food", "bacon": "food", "sausage": "food", "ham": "food",
    "turkey": "food", "pork": "food", "beef": "food", "lamb": "food",
    "mutton": "food", "salmon": "food", "tuna": "food", "cod": "food",
    "shrimp": "food", "lobster": "food", "crab": "food", "oyster": "food",
    "sardine": "food", "trout": "food", "carp": "food", "eel": "food",
    "almond": "food", "peanut": "food", "cashew": "food", "walnut": "food",
    "hazelnut": "food", "pecan": "food", "pistachio": "food", "raisin": "food",
    "fig": "food", "date": "food", "plum": "food", "apricot": "food",
    "kiwi": "food", "papaya": "food", "guava": "food", "lychee": "food",
    "coconut": "food", "avocado": "food", "pomegranate": "food", "blueberry": "food",
    "raspberry": "food", "blackberry": "food", "cranberry": "food", "gooseberry": "food",
    "donut": "food", "muffin": "food", "croissant": "food", "bagel": "food",
    "toast": "food", "pancake": "food", "waffle": "food", "cereal": "food",
    "oatmeal": "food", "porridge": "food", "biscuit": "food", "cracker": "food",
    "chip": "food", "popcorn": "food", "pretzel": "food", "pie": "food",
    "tart": "food", "pudding": "food", "candy": "food", "gum": "food",
    "lollipop": "food", "toffee": "food", "fudge": "food", "brownie": "food",
    "drink": "food", "beverage": "food", "cocktail": "food", "soda": "food",
    "lemonade": "food", "smoothie": "food", "milkshake": "food", "espresso": "food",
    "cappuccino": "food", "latte": "food", "mocha": "food", "whiskey": "food",
    "vodka": "food", "rum": "food", "tequila": "food", "champagne": "food",
    "cider": "food", "punch": "food", "breakfast": "food", "lunch": "food",
    "dinner": "food", "supper": "food", "meal": "food", "snack": "food",
    "appetizer": "food", "dessert": "food", "ingredient": "food", "recipe": "food",
    "menu": "food", "restaurant": "food", "cafe": "food", "cafeteria": "food",
    "diner": "food", "bistro": "food", "bakery": "food", "deli": "food",

    # ===== PEOPLE_ACTION =====
    "run": "people_action", "running": "people_action", "jog": "people_action",
    "jog": "people_action", "jogging": "people_action", "jump": "people_action",
    "jumping": "people_action", "walk": "people_action", "walking": "people_action",
    "swim": "people_action", "swimming": "people_action", "dance": "people_action",
    "dancing": "people_action", "sing": "people_action", "singing": "people_action",
    "read": "people_action", "reading": "people_action", "write": "people_action",
    "writing": "people_action", "study": "people_action", "studying": "people_action",
    "work": "people_action", "working": "people_action", "play": "people_action",
    "playing": "people_action", "sleep": "people_action", "sleeping": "people_action",
    "eat": "people_action", "eating": "people_action", "drink": "people_action",
    "drinking": "people_action", "cook": "people_action", "cooking": "people_action",
    "clean": "people_action", "cleaning": "people_action", "wash": "people_action",
    "washing": "people_action", "drive": "people_action", "driving": "people_action",
    "ride": "people_action", "riding": "people_action", "fly": "people_action",
    "flying": "people_action", "think": "people_action", "thinking": "people_action",
    "learn": "people_action", "learning": "people_action", "teach": "people_action",
    "teaching": "people_action", "help": "people_action", "helping": "people_action",
    "love": "people_action", "loving": "people_action", "laugh": "people_action",
    "laughing": "people_action", "cry": "people_action", "crying": "people_action",
    "shout": "people_action", "shouting": "people_action", "whisper": "people_action",
    "whispering": "people_action", "look": "people_action", "looking": "people_action",
    "watch": "people_action", "watching": "people_action", "see": "people_action",
    "seeing": "people_action", "hear": "people_action", "hearing": "people_action",
    "listen": "people_action", "listening": "people_action", "smell": "people_action",
    "smelling": "people_action", "touch": "people_action", "touching": "people_action",
    "feel": "people_action", "feeling": "people_action", "decide": "people_action",
    "deciding": "people_action", "choose": "people_action", "choosing": "people_action",
    "buy": "people_action", "buying": "people_action", "sell": "people_action",
    "selling": "people_action", "give": "people_action", "giving": "people_action",
    "take": "people_action", "taking": "people_action", "bring": "people_action",
    "bringing": "people_action", "send": "people_action", "sending": "people_action",
    "call": "people_action", "calling": "people_action", "email": "people_action",
    "emailing": "people_action", "message": "people_action", "messaging": "people_action",
    "chat": "people_action", "chatting": "people_action", "meet": "people_action",
    "meeting": "people_action", "greet": "people_action", "greeting": "people_action",
    "fight": "people_action", "fighting": "people_action", "argue": "people_action",
    "arguing": "people_action", "agree": "people_action", "agreeing": "people_action",
    "disagree": "people_action", "build": "people_action", "building": "people_action",
    "make": "people_action", "making": "people_action", "create": "people_action",
    "creating": "people_action", "design": "people_action", "designing": "people_action",
    "paint": "people_action", "painting": "people_action", "draw": "people_action",
    "drawing": "people_action", "photograph": "people_action", "photography": "people_action",
    "film": "people_action", "filming": "people_action", "edit": "people_action",
    "editing": "people_action", "type": "people_action", "typing": "people_action",
    "search": "people_action", "searching": "people_action", "find": "people_action",
    "finding": "people_action", "lose": "people_action", "losing": "people_action",
    "win": "people_action", "winning": "people_action", "fail": "people_action",
    "failing": "people_action", "succeed": "people_action", "succeeding": "people_action",
    "try": "people_action", "trying": "people_action", "attempt": "people_action",
    "attempting": "people_action", "begin": "people_action", "beginning": "people_action",
    "start": "people_action", "starting": "people_action", "stop": "people_action",
    "stopping": "people_action", "end": "people_action", "ending": "people_action",
    "finish": "people_action", "finishing": "people_action", "complete": "people_action",
    "completing": "people_action", "continue": "people_action", "continuing": "people_action",
    "pause": "people_action", "pausing": "people_action", "wait": "people_action",
    "waiting": "people_action", "hurry": "people_action", "hurrying": "people_action",
    "rush": "people_action", "rushing": "people_action", "slow": "people_action",
    "slowing": "people_action", "rest": "people_action", "resting": "people_action",
    "relax": "people_action", "relaxing": "people_action", "meditate": "people_action",
    "meditating": "people_action", "exercise": "people_action", "exercising": "people_action",
    "train": "people_action", "training": "people_action", "practice": "people_action",
    "practicing": "people_action", "compete": "people_action", "competing": "people_action",
    "competing": "people_action", "compete": "people_action", "race": "people_action",
    "racing": "people_action", "score": "people_action", "scoring": "people_action",
    "kick": "people_action", "kicking": "people_action", "throw": "people_action",
    "throwing": "people_action", "catch": "people_action", "catching": "people_action",
    "hit": "people_action", "hitting": "people_action", "shoot": "people_action",
    "shooting": "people_action", "defend": "people_action", "defending": "people_action",
    "attack": "people_action", "attacking": "people_action", "protect": "people_action",
    "protecting": "people_action", "save": "people_action", "saving": "people_action",
    "rescue": "people_action", "rescuing": "people_action", "heal": "people_action",
    "healing": "people_action", "cure": "people_action", "curing": "people_action",
    "treat": "people_action", "treating": "people_action", "nurse": "people_action",
    "nursing": "people_action", "doctor": "people_action", "patient": "people_action",
    "doctor": "people_action", "lawyer": "people_action", "judge": "people_action",
    "officer": "people_action", "police": "people_action", "soldier": "people_action",
    "firefighter": "people_action", "teacher": "people_action", "student": "people_action",
    "engineer": "people_action", "scientist": "people_action", "artist": "people_action",
    "musician": "people_action", "singer": "people_action", "dancer": "people_action",
    "actor": "people_action", "actress": "people_action", "writer": "people_action",
    "author": "people_action", "poet": "people_action", "journalist": "people_action",
    "reporter": "people_action", "editor": "people_action", "publisher": "people_action",
    "manager": "people_action", "boss": "people_action", "leader": "people_action",
    "follower": "people_action", "member": "people_action", "team": "people_action",
    "staff": "people_action", "crew": "people_action", "colleague": "people_action",
    "partner": "people_action", "assistant": "people_action", "secretary": "people_action",
    "accountant": "people_action", "cashier": "people_action", "clerk": "people_action",
    "salesperson": "people_action", "waiter": "people_action", "waitress": "people_action",
    "chef": "people_action", "cook": "people_action", "baker": "people_action",
    "butcher": "people_action", "fisherman": "people_action", "farmer": "people_action",
    "driver": "people_action", "pilot": "people_action", "captain": "people_action",
    "sailor": "people_action", "soldier": "people_action", "general": "people_action",
    "president": "people_action", "minister": "people_action", "governor": "people_action",
    "mayor": "people_action", "senator": "people_action", "congressman": "people_action",
    "representative": "people_action", "diplomat": "people_action", "ambassador": "people_action",
    "athlete": "people_action", "player": "people_action", "coach": "people_action",
    "trainer": "people_action", "referee": "people_action", "umpire": "people_action",
    "fan": "people_action", "supporter": "people_action", "spectator": "people_action",
    "audience": "people_action", "crowd": "people_action", "mob": "people_action",

    # ===== PLACE =====
    "school": "place", "hospital": "place", "library": "place", "park": "place",
    "garden": "place", "beach": "place", "mountain": "place", "river": "place",
    "sea": "place", "ocean": "place", "lake": "place", "forest": "place",
    "desert": "place", "city": "place", "town": "place", "village": "place",
    "road": "place", "street": "place", "bridge": "place", "airport": "place",
    "station": "place", "hotel": "place", "restaurant": "place", "cafe": "place",
    "shop": "place", "mall": "place", "market": "place", "office": "place",
    "factory": "place", "farm": "place", "field": "place", "zoo": "place",
    "museum": "place", "theater": "place", "church": "place", "temple": "place",
    "mosque": "place", "building": "place", "house": "place", "home": "place",
    "apartment": "place", "room": "place", "kitchen": "place", "bedroom": "place",
    "bathroom": "place", "garage": "place", "yard": "place", "pool": "place",
    "playground": "place", "stadium": "place", "gym": "place", "arena": "place",
    "hall": "place", "auditorium": "place", "cinema": "place", "theatre": "place",
    "gallery": "place", "exhibition": "place", "studio": "place", "workshop": "place",
    "warehouse": "place", "store": "place", "boutique": "place", "supermarket": "place",
    "department": "place", "pharmacy": "place", "drugstore": "place", "bakery": "place",
    "butcher": "place", "florist": "place", "jeweler": "place", "optician": "place",
    "bank": "place", "postoffice": "place", "post": "place", "courthouse": "place",
    "prison": "place", "jail": "place", "embassy": "place", "consulate": "place",
    "parliament": "place", "capitol": "place", "palace": "place", "castle": "place",
    "fortress": "place", "tower": "place", "wall": "place", "gate": "place",
    "harbor": "place", "port": "place", "dock": "place", "pier": "place",
    "wharf": "place", "marina": "place", "lighthouse": "place", "island": "place",
    "peninsula": "place", "continent": "place", "country": "place", "state": "place",
    "province": "place", "county": "place", "district": "place", "neighborhood": "place",
    "suburb": "place", "downtown": "place", "uptown": "place", "highway": "place",
    "freeway": "place", "expressway": "place", "alley": "place", "lane": "place",
    "avenue": "place", "boulevard": "place", "intersection": "place", "crossroad": "place",
    "roundabout": "place", "tunnel": "place", "viaduct": "place", "overpass": "place",
    "underpass": "place", "sidewalk": "place", "pavement": "place", "curb": "place",
    "highway": "place", "railway": "place", "railroad": "place", "subway": "place",
    "metro": "place", "tram": "place", "bus": "place", "taxi": "place",
    "cab": "place", "terminal": "place", "stop": "place", "platform": "place",

    # ===== OBJECT =====
    "book": "object", "pen": "object", "pencil": "object", "paper": "object",
    "notebook": "object", "computer": "object", "phone": "object", "tablet": "object",
    "keyboard": "object", "mouse": "object", "monitor": "object", "tv": "object",
    "television": "object", "radio": "object", "clock": "object", "watch": "object",
    "umbrella": "object", "bag": "object", "backpack": "object", "wallet": "object",
    "key": "object", "door": "object", "window": "object", "table": "object",
    "chair": "object", "sofa": "object", "bed": "object", "lamp": "object",
    "cup": "object", "bowl": "object", "plate": "object", "knife": "object",
    "fork": "object", "spoon": "object", "bottle": "object", "box": "object",
    "ball": "object", "racket": "object", "bicycle": "object", "bike": "object",
    "car": "object", "bus": "object", "train": "object", "plane": "object",
    "airplane": "object", "boat": "object", "ship": "object", "rocket": "object",
    "rocket": "object", "spaceship": "object", "helicopter": "object", "motorcycle": "object",
    "scooter": "object", "skateboard": "object", "wagon": "object", "cart": "object",
    "trolley": "object", "truck": "object", "van": "object", "jeep": "object",
    "sedan": "object", "coupe": "object", "suv": "object", "convertible": "object",
    "piano": "object", "guitar": "object", "violin": "object", "drum": "object",
    "flute": "object", "trumpet": "object", "saxophone": "object", "harp": "object",
    "microphone": "object", "speaker": "object", "headphone": "object", "headset": "object",
    "earphone": "object", "earbud": "object", "camera": "object", "lens": "object",
    "tripod": "object", "battery": "object", "charger": "object", "cable": "object",
    "wire": "object", "plug": "object", "socket": "object", "switch": "object",
    "button": "object", "knob": "object", "lever": "object", "handle": "object",
    "lock": "object", "chain": "object", "rope": "object", "string": "object",
    "tape": "object", "glue": "object", "scissors": "object", "knife": "object",
    "saw": "object", "hammer": "object", "nail": "object", "screw": "object",
    "wrench": "object", "tool": "object", "drill": "object", "axe": "object",
    "shovel": "object", "rake": "object", "broom": "object", "mop": "object",
    "bucket": "object", "basket": "object", "tray": "object", "rack": "object",
    "shelf": "object", "cabinet": "object", "drawer": "object", "wardrobe": "object",
    "closet": "object", "mirror": "object", "frame": "object", "painting": "object",
    "poster": "object", "calendar": "object", "map": "object", "globe": "object",
    "atlas": "object", "dictionary": "object", "magazine": "object", "newspaper": "object",
    "letter": "object", "envelope": "object", "stamp": "object", "card": "object",
    "ticket": "object", "passport": "object", "license": "object", "certificate": "object",
    "document": "object", "folder": "object", "file": "object", "binder": "object",
    "clip": "object", "pin": "object", "stapler": "object", "ruler": "object",
    "compass": "object", "calculator": "object", "abacus": "object", "eraser": "object",
    "sharpener": "object", "marker": "object", "crayon": "object", "paint": "object",
    "brush": "object", "canvas": "object", "easel": "object", "palette": "object",
    "doll": "object", "toy": "object", "puzzle": "object", "game": "object",
    "board": "object", "dice": "object", "chess": "object", "card": "object",
    "kite": "object", "yo-yo": "object", "top": "object", "marble": "object",
    "balloon": "object", "kite": "object", "tent": "object", "sleeping": "object",

    # ===== NATURE =====
    "sun": "nature", "moon": "nature", "star": "nature", "cloud": "nature",
    "rain": "nature", "snow": "nature", "wind": "nature", "storm": "nature",
    "thunder": "nature", "lightning": "nature", "rainbow": "nature", "flower": "nature",
    "tree": "nature", "grass": "nature", "leaf": "nature", "seed": "nature",
    "root": "nature", "sky": "nature", "volcano": "nature", "island": "nature",
    "cave": "nature", "waterfall": "nature", "earthquake": "nature", "tsunami": "nature",
    "flood": "nature", "drought": "nature", "tornado": "nature", "hurricane": "nature",
    "typhoon": "nature", "cyclone": "nature", "blizzard": "nature", "hail": "nature",
    "fog": "nature", "mist": "nature", "dew": "nature", "frost": "nature",
    "iceberg": "nature", "glacier": "nature", "cliff": "nature", "valley": "nature",
    "hill": "nature", "ridge": "nature", "peak": "nature", "summit": "nature",
    "plateau": "nature", "plain": "nature", "meadow": "nature", "prairie": "nature",
    "steppe": "nature", "tundra": "nature", "swamp": "nature", "marsh": "nature",
    "bog": "nature", "wetland": "nature", "pond": "nature", "creek": "nature",
    "stream": "nature", "brook": "nature", "spring": "nature", "waterfall": "nature",
    "rapids": "nature", "delta": "nature", "estuary": "nature", "bay": "nature",
    "cove": "nature", "lagoon": "nature", "reef": "nature", "coral": "nature",
    "shore": "nature", "coast": "nature", "dune": "nature", "beach": "nature",
    "rose": "nature", "tulip": "nature", "lily": "nature", "daisy": "nature",
    "sunflower": "nature", "orchid": "nature", "cactus": "nature", "bamboo": "nature",
    "oak": "nature", "maple": "nature", "pine": "nature", "birch": "nature",
    "willow": "nature", "elm": "nature", "cedar": "nature", "redwood": "nature",
    "sequoia": "nature", "fern": "nature", "moss": "nature", "ivy": "nature",
    "vine": "nature", "bush": "nature", "shrub": "nature", "weed": "nature",
    "wildflower": "nature", "blossom": "nature", "petal": "nature", "thorn": "nature",
    "branch": "nature", "trunk": "nature", "bark": "nature", "fruit": "nature",
    "berry": "nature", "acorn": "nature", "pinecone": "nature", "log": "nature",

    # ===== ABSTRACT =====
    "time": "abstract", "space": "abstract", "energy": "abstract", "power": "abstract",
    "love": "abstract", "peace": "abstract", "war": "abstract", "freedom": "abstract",
    "justice": "abstract", "truth": "abstract", "lie": "abstract", "dream": "abstract",
    "hope": "abstract", "fear": "abstract", "joy": "abstract", "sadness": "abstract",
    "anger": "abstract", "surprise": "abstract", "disgust": "abstract", "success": "abstract",
    "failure": "abstract", "luck": "abstract", "chance": "abstract", "idea": "abstract",
    "thought": "abstract", "memory": "abstract", "imagination": "abstract", "creativity": "abstract",
    "wisdom": "abstract", "knowledge": "abstract", "skill": "abstract", "strength": "abstract",
    "beauty": "abstract", "art": "abstract", "music": "abstract", "sport": "abstract",
    "health": "abstract", "safety": "abstract", "danger": "abstract", "money": "abstract",
    "wealth": "abstract", "family": "abstract", "friend": "abstract", "team": "abstract",
    "community": "abstract", "culture": "abstract", "history": "abstract", "future": "abstract",
    "past": "abstract", "present": "abstract", "philosophy": "abstract", "religion": "abstract",
    "faith": "abstract", "belief": "abstract", "doubt": "abstract", "trust": "abstract",
    "honor": "abstract", "pride": "abstract", "shame": "abstract", "guilt": "abstract",
    "regret": "abstract", "envy": "abstract", "jealousy": "abstract", "hatred": "abstract",
    "compassion": "abstract", "sympathy": "abstract", "empathy": "abstract", "mercy": "abstract",
    "forgiveness": "abstract", "patience": "abstract", "courage": "abstract", "bravery": "abstract",
    "honesty": "abstract", "loyalty": "abstract", "kindness": "abstract", "generosity": "abstract",
    "humility": "abstract", "modesty": "abstract", "arrogance": "abstract", "stubbornness": "abstract",
    "discipline": "abstract", "responsibility": "abstract", "obligation": "abstract", "duty": "abstract",
    "right": "abstract", "wrong": "abstract", "good": "abstract", "bad": "abstract",
    "evil": "abstract", "sin": "abstract", "virtue": "abstract", "morality": "abstract",
    "ethics": "abstract", "logic": "abstract", "reason": "abstract", "rationality": "abstract",
    "intuition": "abstract", "instinct": "abstract", "consciousness": "abstract", "mind": "abstract",
    "soul": "abstract", "spirit": "abstract", "heart": "abstract", "brain": "abstract",
    "body": "abstract", "intellect": "abstract", "intelligence": "abstract", "genius": "abstract",
    "talent": "abstract", "gifts": "abstract", "fate": "abstract", "destiny": "abstract",
    "destiny": "abstract", "karma": "abstract", "destiny": "abstract", "fate": "abstract",
    "opportunity": "abstract", "risk": "abstract", "threat": "abstract", "crisis": "abstract",
    "problem": "abstract", "solution": "abstract", "answer": "abstract", "question": "abstract",
    "issue": "abstract", "matter": "abstract", "topic": "abstract", "subject": "abstract",
    "theme": "abstract", "concept": "abstract", "theory": "abstract", "hypothesis": "abstract",
    "experiment": "abstract", "research": "abstract", "analysis": "abstract", "method": "abstract",
    "system": "abstract", "structure": "abstract", "pattern": "abstract", "model": "abstract",
    "design": "abstract", "plan": "abstract", "strategy": "abstract", "policy": "abstract",
    "rule": "abstract", "law": "abstract", "regulation": "abstract", "standard": "abstract",
    "principle": "abstract", "value": "abstract", "principle": "abstract", "norm": "abstract",
    "tradition": "abstract", "custom": "abstract", "habit": "abstract", "ritual": "abstract",
    "ceremony": "abstract", "festival": "abstract", "celebration": "abstract", "holiday": "abstract",
    "anniversary": "abstract", "birthday": "abstract", "wedding": "abstract", "funeral": "abstract",
    "graduation": "abstract", "promotion": "abstract", "achievement": "abstract", "award": "abstract",
    "prize": "abstract", "reward": "abstract", "punishment": "abstract", "penalty": "abstract",
    "fine": "abstract", "fee": "abstract", "cost": "abstract", "price": "abstract",
    "value": "abstract", "worth": "abstract", "profit": "abstract", "loss": "abstract",
    "gain": "abstract", "income": "abstract", "expense": "abstract", "budget": "abstract",
    "salary": "abstract", "wage": "abstract", "bonus": "abstract", "pension": "abstract",
    "tax": "abstract", "debt": "abstract", "loan": "abstract", "mortgage": "abstract",
    "insurance": "abstract", "investment": "abstract", "stock": "abstract", "bond": "abstract",
    "currency": "abstract", "cash": "abstract", "coin": "abstract", "check": "abstract",
    "contract": "abstract", "agreement": "abstract", "treaty": "abstract", "deal": "abstract",

    # ===== EMOTION_COLOR =====
    "red": "emotion_color", "blue": "emotion_color", "green": "emotion_color",
    "yellow": "emotion_color", "orange": "emotion_color", "purple": "emotion_color",
    "pink": "emotion_color", "black": "emotion_color", "white": "emotion_color",
    "gray": "emotion_color", "grey": "emotion_color", "brown": "emotion_color",
    "happy": "emotion_color", "sad": "emotion_color", "angry": "emotion_color",
    "surprised": "emotion_color", "scared": "emotion_color", "afraid": "emotion_color",
    "confused": "emotion_color", "excited": "emotion_color", "bored": "emotion_color",
    "calm": "emotion_color", "tired": "emotion_color", "anxious": "emotion_color",
    "nervous": "emotion_color", "worried": "emotion_color", "relaxed": "emotion_color",
    "proud": "emotion_color", "embarrassed": "emotion_color", "ashamed": "emotion_color",
    "jealous": "emotion_color", "envious": "emotion_color", "grateful": "emotion_color",
    "thankful": "emotion_color", "lonely": "emotion_color", "depressed": "emotion_color",
    "cheerful": "emotion_color", "gloomy": "emotion_color", "irritated": "emotion_color",
    "annoyed": "emotion_color", "furious": "emotion_color", "delighted": "emotion_color",
    "ecstatic": "emotion_color", "enthusiastic": "emotion_color", "passionate": "emotion_color",
    "indifferent": "emotion_color", "apathetic": "emotion_color", "curious": "emotion_color",
    "interested": "emotion_color", "boring": "emotion_color", "amusing": "emotion_color",
    "circle": "emotion_color", "square": "emotion_color", "triangle": "emotion_color",
    "rectangle": "emotion_color", "oval": "emotion_color", "diamond": "emotion_color",
    "heart": "emotion_color", "cross": "emotion_color", "spade": "emotion_color",
    "club": "emotion_color", "spade": "emotion_color", "ace": "emotion_color",
    "king": "emotion_color", "queen": "emotion_color", "jack": "emotion_color",
    "joker": "emotion_color", "color": "emotion_color", "colour": "emotion_color",
    "shade": "emotion_color", "tone": "emotion_color", "hue": "emotion_color",
    "tint": "emotion_color", "bright": "emotion_color", "dark": "emotion_color",
    "light": "emotion_color", "gold": "emotion_color", "silver": "emotion_color",
    "bronze": "emotion_color", "copper": "emotion_color", "tan": "emotion_color",
    "beige": "emotion_color", "cream": "emotion_color", "ivory": "emotion_color",
    "khaki": "emotion_color", "navy": "emotion_color", "teal": "emotion_color",
    "cyan": "emotion_color", "magenta": "emotion_color", "maroon": "emotion_color",
    "olive": "emotion_color", "lime": "emotion_color", "indigo": "emotion_color",
    "violet": "emotion_color", "crimson": "emotion_color", "scarlet": "emotion_color",
    "azure": "emotion_color", "aqua": "emotion_color", "lavender": "emotion_color",
    "plum": "emotion_color", "rust": "emotion_color", "rose": "emotion_color",
    "salmon": "emotion_color", "turquoise": "emotion_color", "transparent": "emotion_color",
    "opaque": "emotion_color", "shiny": "emotion_color", "dull": "emotion_color",
    "matte": "emotion_color", "glossy": "emotion_color", "metallic": "emotion_color",
    "fluorescent": "emotion_color", "pastel": "emotion_color", "neon": "emotion_color",
    "feel": "emotion_color", "feeling": "emotion_color", "mood": "emotion_color",
    "emotion": "emotion_color", "passion": "emotion_color", "sentiment": "emotion_color",
}


_SUFFIX_RULES = [
    (r".+tion$", "abstract"),
    (r".+sion$", "abstract"),
    (r".+ment$", "abstract"),
    (r".+ness$", "abstract"),
    (r".+ity$", "abstract"),
    (r".+ism$", "abstract"),
    (r".+ist$", "abstract"),
    (r".+ence$", "abstract"),
    (r".+ance$", "abstract"),
    (r".+ology$", "abstract"),
    (r".+ography$", "abstract"),
    (r".+er$", "people_action"),
    (r".+or$", "people_action"),
    (r".+ist$", "people_action"),
    (r".+ant$", "people_action"),
    (r".+ent$", "people_action"),
    (r".+ing$", "people_action"),
    (r".+ed$", "people_action"),
    (r".+ly$", "emotion_color"),
]


def get_category(word: str) -> str:
    """Return deterministic category for the word."""
    w = word.lower().strip()
    if not w:
        return "fallback"
    if w in WORD_TO_CAT:
        return WORD_TO_CAT[w]
    # try suffix rules
    for pat, cat in _SUFFIX_RULES:
        if re.match(pat, w):
            return cat
    # short word (<=4) - default abstract
    if len(w) <= 4 and w.isalpha():
        return "abstract"
    # hash-based fallback to make it deterministic but spread across categories
    h = int(hashlib.md5(w.encode("utf-8")).hexdigest(), 16)
    # Use mod 7 to map hash to one of 7 main cats (excluding fallback)
    return ["animal", "food", "people_action", "place", "object", "nature", "abstract"][h % 7]


if __name__ == "__main__":
    test = ["apple", "happy", "democracy", "achy", "zebra", "running", "education",
            "computer", "beach", "rainbow", "red", "alpha", "betaword", "gamma",
            "xylophone", "unknownword", "zxcvbnm", "asdf", "thinking"]
    for t in test:
        print(t, "->", get_category(t))
    print("Total mapped:", len(WORD_TO_CAT))
